name: Refresh Dependencies Target

on:
  push:
    branches: [ master ]

jobs:
  refresh:
    name: Merge and push
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]
  
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: git pull origin dependency-updates
      - run: git checkout dependency-updates
      - run: git merge master
      - run: git push origin dependency-updates
