name: Refresh dependencies target

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git branch -a
          git checkout dependency-updates
          git merge master
          git push origin dependency-updates
