name: Refresh dependencies target

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git branch -a
      - run: git pull origin dependency-updates
      - run: git checkout dependency-updates
